### PR TITLE
Rename podspec 

### PR DESCRIPTION
**Pull request by Eddayy**
Rename podspec file to fit new name

### CODE REVIEW

**Comment by nicmaster** [comment]
Hi there
I having this issue trying to use your downloads_path_provider_28: ^0.1.0
   Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `downloads_path_provider_28` from `.symlinks/plugins/downloads_path_provider_28/ios`
    [!] No podspec found for `downloads_path_provider_28` in `.symlinks/plugins/downloads_path_provider_28/ios`

**Comment by HetalGohil** [comment]
how to solve this..you have found anything..i m also getting this error...can you help please

**Comment by h-rub** [comment]
> Hi there
> I having this issue trying to use your downloads_path_provider_28: ^0.1.0
> Fetching external sources
> -> Fetching podspec for `Flutter` from `Flutter`
> -> Fetching podspec for `downloads_path_provider_28` from `.symlinks/plugins/downloads_path_provider_28/ios`
> [!] No podspec found for `downloads_path_provider_28` in `.symlinks/plugins/downloads_path_provider_28/ios`

Same problem, ¿how can fix it?

**Comment by devinyonas** [comment]
go to `.symlinks/plugins/downloads_path_provider_28/ios` folder from Flutter `ios` folder. rename the podspec file by adding `_28`

folder path: `ios/.symlinks/plugins/downloads_path_provider_28/ios/`
file to rename: `downloads_path_provider.podspec` to `downloads_path_provider_28.podspec`

path screenshot: 
image

**Comment by mw66** [comment]
@chitgoks  can you merge this PR and make a new release?  It has been for a while now.

Thanks!

**Comment by chitgoks** [comment]
I actually am not using this anymore. but ill go ahead and merge it

**Comment by chitgoks** [comment]
Published this to pub.dev.

**Pull request merged**
